<center><h1>Hong_Brandon_HW3</h1></center>
<br>
<br>

Name: Brandon Hong
<br>
Github Username: bwhong
<br>
USC ID: 3091232124

## 1. Time Series Classification Part 1: Feature Creation/Extraction

### (a) Download Data

Package imports

In [ ]:
import pandas as pd
import numpy as np

Get the AReM Data Set

In [158]:
instances = []
instance_counter = 1

In [159]:
bending1_datasets = []
for i in np.arange(1,8,1):
    bending1_datasets.append('../data/AReM/bending1/' + f'dataset{i}.csv')
for dataset in bending1_datasets:
    temp_dataset = pd.read_csv(dataset, skiprows=4)
    temp_dataset['instance_number'] = instance_counter
    instance_counter += 1
    instances.append(temp_dataset)

In [160]:
bending2_datasets = []
for i in np.arange(1,7,1):
    bending2_datasets.append('../data/AReM/bending2/' + f'dataset{i}.csv')
for dataset in bending2_datasets:
    if dataset == '../data/AReM/bending2/dataset4.csv':
        with open(dataset, "r") as file:
            column_names = file.readlines()[4].strip().split(",")
        temp_dataset = pd.read_csv(dataset, delimiter= ' ', skiprows = 5, names = column_names, index_col=False)
    else:
        temp_dataset = pd.read_csv(dataset, skiprows=4)
    temp_dataset['instance_number'] = instance_counter
    instance_counter += 1
    instances.append(temp_dataset)

In [161]:
cycling_datasets = []
for i in np.arange(1,16,1):
    cycling_datasets.append('../data/AReM/cycling/' + f'dataset{i}.csv')
for dataset in cycling_datasets:
    temp_dataset = pd.read_csv(dataset, skiprows=4, usecols=range(7))
    temp_dataset['instance_number'] = instance_counter
    instance_counter += 1
    instances.append(temp_dataset)

In [162]:
lying_datasets = []
for i in np.arange(1,16,1):
    lying_datasets.append('../data/AReM/lying/' + f'dataset{i}.csv')
for dataset in lying_datasets:
    temp_dataset = pd.read_csv(dataset, skiprows=4, usecols=range(7))
    temp_dataset['instance_number'] = instance_counter
    instance_counter += 1
    instances.append(temp_dataset)

In [163]:
sitting_datasets = []
for i in np.arange(1,16,1):
    sitting_datasets.append('../data/AReM/sitting/' + f'dataset{i}.csv')
for dataset in sitting_datasets:
    temp_dataset = pd.read_csv(dataset, skiprows=4, usecols=range(7))
    temp_dataset['instance_number'] = instance_counter
    instance_counter += 1
    instances.append(temp_dataset)

In [164]:
standing_datasets = []
for i in np.arange(1,16,1):
    standing_datasets.append('../data/AReM/standing/' + f'dataset{i}.csv')
for dataset in standing_datasets:
    temp_dataset = pd.read_csv(dataset, skiprows=4, usecols=range(7))
    temp_dataset['instance_number'] = instance_counter
    instance_counter += 1
    instances.append(temp_dataset)

In [165]:
walking_datasets = []
for i in np.arange(1,16,1):
    walking_datasets.append('../data/AReM/walking/' + f'dataset{i}.csv')
for dataset in walking_datasets:
    temp_dataset = pd.read_csv(dataset, skiprows=4, usecols=range(7))
    temp_dataset['instance_number'] = instance_counter
    instance_counter += 1
    instances.append(temp_dataset)

### (b) Test and Train Data

In [166]:
#test data is first 2 in bending 1 and 2, and then first 3 in every other folder
test_instances = [0,1,7,8,13,14,15,28,29,30,44,45,46, 59, 60, 61, 74, 75, 76]
test_data = pd.concat(instances[i] for i in test_instances)
test_data

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23,instance_number
0,0,39.25,0.43,22.75,0.43,33.75,1.30,1
1,250,39.25,0.43,23.00,0.00,33.00,0.00,1
2,500,39.25,0.43,23.25,0.43,33.00,0.00,1
3,750,39.50,0.50,23.00,0.71,33.00,0.00,1
4,1000,39.50,0.50,24.00,0.00,33.00,0.00,1
...,...,...,...,...,...,...,...,...
475,118750,34.75,7.66,14.50,2.18,12.00,5.79,77
476,119000,24.75,8.26,13.50,5.02,17.25,4.32,77
477,119250,26.25,2.49,18.75,3.56,12.50,7.09,77
478,119500,38.50,3.28,18.25,2.38,18.50,2.06,77
479,119750,35.50,1.50,14.00,2.12,20.75,3.27,77

In [167]:
# train data is everything not in test
train_data = pd.concat(instances[i] for i in range(88) if i not in test_instances)
train_data

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23,instance_number
0,0,42.00,0.71,21.25,0.43,30.00,0.00,3
1,250,41.50,0.50,20.25,1.48,31.25,1.09,3
2,500,41.50,0.50,14.25,1.92,33.00,0.00,3
3,750,40.75,0.83,15.75,0.43,33.00,0.00,3
4,1000,40.00,0.71,20.00,2.74,32.75,0.43,3
...,...,...,...,...,...,...,...,...
475,118750,34.50,6.18,9.00,3.56,12.67,4.19,88
476,119000,25.75,6.02,13.75,2.05,16.00,1.58,88
477,119250,31.50,3.35,10.25,5.12,16.25,2.95,88
478,119500,33.75,2.77,14.00,3.24,13.75,0.43,88
479,119750,37.00,1.41,18.25,3.70,11.00,4.32,88

### (c) Feature Extraction

#### i. Research

Mean, Standard Deviation, Skewness, Kurtosis, Maximum, Minimum, Quantiles, Median

#### ii. Extraction

In [168]:
all_column_names = []
for i in np.arange(1,7,1):
    all_column_names.extend([f'min_{i}', f'max_{i}', f'mean_{i}', f'median_{i}', f'std_{i}', f'1st_quart_{i}', f'3rd_quart_{i}'])
all_column_names

['min_1',
 'max_1',
 'mean_1',
 'median_1',
 'std_1',
 '1st_quart_1',
 '3rd_quart_1',
 'min_2',
 'max_2',
 'mean_2',
 'median_2',
 'std_2',
 '1st_quart_2',
 '3rd_quart_2',
 'min_3',
 'max_3',
 'mean_3',
 'median_3',
 'std_3',
 '1st_quart_3',
 '3rd_quart_3',
 'min_4',
 'max_4',
 'mean_4',
 'median_4',
 'std_4',
 '1st_quart_4',
 '3rd_quart_4',
 'min_5',
 'max_5',
 'mean_5',
 'median_5',
 'std_5',
 '1st_quart_5',
 '3rd_quart_5',
 'min_6',
 'max_6',
 'mean_6',
 'median_6',
 'std_6',
 '1st_quart_6',
 '3rd_quart_6']

In [169]:
extraction = []
for i in np.arange(0,88, 1):
    stats = instances[i].drop(columns = {'# Columns: time', 'instance_number'}).describe().T[['min', 'max', 'mean', '50%', 'std', '25%', '75%']].rename(columns = {'50%':'median', '25%': '1st_quart', '75%': '3rd_quart'}).to_numpy().flatten()
    extraction.append(stats)
time_series_stats = pd.DataFrame(extraction, columns= all_column_names)
time_series_stats.insert(0, 'Instance', np.arange(1,89,1))
time_series_stats

,Instance,min_1,max_1,mean_1,median_1,std_1,1st_quart_1,3rd_quart_1,min_2,max_2,...,std_5,1st_quart_5,3rd_quart_5,min_6,max_6,mean_6,median_6,std_6,1st_quart_6,3rd_quart_6
0,1,37.25,45.00,40.624792,40.50,1.476967,39.25,42.0000,0.0,1.30,...,2.188449,33.0000,36.00,0.00,1.92,0.570583,0.43,0.582915,0.0000,1.3000
1,2,38.00,45.67,42.812812,42.50,1.435550,42.00,43.6700,0.0,1.22,...,1.995255,32.0000,34.50,0.00,3.11,0.571083,0.43,0.601010,0.0000,1.3000
2,3,35.00,47.40,43.954500,44.33,1.558835,43.00,45.0000,0.0,1.70,...,1.999604,35.3625,36.50,0.00,1.79,0.493292,0.43,0.513506,0.0000,0.9400
3,4,33.00,47.75,42.179812,43.50,3.670666,39.15,45.0000,0.0,3.00,...,3.849448,30.4575,36.33,0.00,2.18,0.613521,0.50,0.524317,0.0000,1.0000
4,5,33.00,45.75,41.678063,41.75,2.243490,41.33,42.7500,0.0,2.83,...,2.411026,28.4575,31.25,0.00,1.79,0.383292,0.43,0.389164,0.0000,0.5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,84,19.50,45.33,33.586875,34.25,4.650935,30.25,37.0000,0.0,14.67,...,3.283983,13.7300,18.25,0.00,8.32,3.259729,3.11,1.640243,2.0500,4.3225
84,85,19.75,45.50,34.322750,35.25,4.752477,31.00,38.0000,0.0,13.47,...,3.119856,13.5000,17.75,0.00,9.67,3.432563,3.20,1.732727,2.1575,4.5650
85,86,19.50,46.00,34.546229,35.25,4.842294,31.25,37.8125,0.0,12.47,...,2.823124,14.0000,17.75,0.00,10.00,3.338125,3.08,1.656742,2.1600,4.3350
86,87,23.50,46.25,34.873229,35.25,4.531720,31.75,38.2500,0.0,14.82,...,3.131076,13.7500,18.00,0.00,9.51,3.424646,3.27,1.690960,2.1700,4.5000
87,88,19.25,44.00,34.473188,35.00,4.796705,31.25,38.0000,0.0,13.86,...,3.156320,13.7300,17.75,0.43,9.00,3.340458,3.09,1.699114,2.1200,4.3750

#### iii. Standard Deviation

In [170]:
time_series_stats.drop(columns = {'Instance'}).std()

min_1          9.569975
max_1          4.394362
mean_1         5.335718
median_1       5.440054
std_1          1.772153
1st_quart_1    6.153590
3rd_quart_1    5.138925
min_2          0.000000
max_2          5.062729
mean_2         1.574164
median_2       1.412244
std_2          0.884105
1st_quart_2    0.946386
3rd_quart_2    2.125266
min_3          2.956462
max_3          4.875137
mean_3         4.008380
median_3       4.036396
std_3          0.946710
1st_quart_3    4.220658
3rd_quart_3    4.171628
min_4          0.000000
max_4          2.183625
mean_4         1.166114
median_4       1.145586
std_4          0.458242
1st_quart_4    0.843620
3rd_quart_4    1.552504
min_5          6.124001
max_5          5.741238
mean_5         5.675593
median_5       5.813782
std_5          1.024898
1st_quart_5    6.096465
3rd_quart_5    5.531720
min_6          0.045838
max_6          2.518921
mean_6         1.154812
median_6       1.086474
std_6          0.517617
1st_quart_6    0.758584
3rd_quart_6    1.523599
dtype: float64

In [ ]:
length = time_series_stats.shape[0]
bootstrap_std = {}

for i in time_series_stats.columns[1:]:
    bootstrap_std[f'{i}_bootstrap_std'] = []
    for j in np.arange(0,1000, 1):
        sample_std = time_series_stats[f'{i}'].sample(n = length, replace = True).std()
        bootstrap_std[f'{i}_bootstrap_std'].append(sample_std)

bootstrap_std

{'min_1_bootstrap_std': [10.706373317973947,
  8.840907977478823,
  9.70146777008198,
  8.902140570661185,
  9.652170848563769,
  10.385403389024862,
  9.21761456523594,
  8.568987349776341,
  9.004247642131793,
  9.491982215772163,
  9.304938607932222,
  9.403259742379454,
  7.984819000434323,
  10.005404902334819,
  9.78436131981958,
  9.878614244087585,
  9.633160495858872,
  8.655119002065565,
  10.40679470122768,
  9.134115686999484,
  8.62907121290511,
  9.261674001825586,
  8.853314795211672,
  9.17670201442471,
  10.45942250174504,
  9.85322781729623,
  10.236219591381797,
  10.856288153113264,
  9.03845848899948,
  10.910469136043032,
  8.932885635001998,
  9.064981312382,
  9.605704480590848,
  10.296132684789976,
  8.602404884007802,
  9.795796061610753,
  10.13132571079951,
  10.782377064421006,
  9.38357793148425,
  10.271143567180747,
  8.510303141553099,
  10.718215179071066,
  7.757816854533552,
  9.020548801442505,
  8.831760546876641,
  9.483133390404724,
  8.5897137063437,
  10.454164971723392,
  8.27046735383096,
  10.459666874519204,
  8.397749679137782,
  8.696238557389163,
  8.763165690730577,
  10.369473917640715,
  8.201778548327148,
  8.941018551323431,
  10.790438707001245,
  8.64489856801722,
  9.533057131131265,
  9.062765683058283,
  9.143430471168179,
  9.166010903921324,
  9.136334422927243,
  9.06317310547536,
  8.478320142262367,
  9.98375300604359,
  8.629655253311894,
  8.030187330030442,
  9.724292118711332,
  10.109685869519154,
  9.159489776455606,
  9.2434269332722,
  10.05128009478828,
  9.489645635196775,
  9.325254279914166,
  10.040813889352101,
  9.180880156571089,
  10.220646771531738,
  8.573994726314893,
  10.674708157125979,
  9.692110602362222,
  9.610571530814534,
  9.922402684134692,
  9.19383612684459,
  9.167095816875621,
  10.076945028510771,
  9.885280360365623,
  9.527931462386428,
  10.03581814143845,
  8.627888627027883,
  9.624561958575667,
  10.407330857618454,
  11.303044207621971,
  10.242340619518993,
  9.739199725093766,
  8.449908990717631,
  8.25328180743872,
  8.707426609562638,
  9.871531113672951,
  10.883946159343013,
  9.468791243603514,
  9.442704193552732,
  10.306928541204723,
  8.447459214229509,
  9.423463539814165,
  9.647639636805003,
  9.296280115249928,
  8.770980917578767,
  7.995010368444561,
  9.655108100621753,
  9.462741972186702,
  10.368439613601398,
  10.073686319347356,
  9.370416747310992,
  8.78064625123582,
  9.560950709756806,
  9.432024670978091,
  8.59337037301524,
  10.079946674502551,
  7.893405484559763,
  9.198200626333282,
  9.830038628793567,
  11.153165809569836,
  10.098008928794766,
  9.414879438732742,
  8.401480717846772,
  9.822174300720304,
  8.267439422076292,
  9.018090102607427,
  8.53931222590766,
  8.927324391672364,
  10.349615931747987,
  9.861122167099536,
  9.679421647764613,
  8.840831384488988,
  10.239172755900881,
  9.42248413713308,
  7.747168390080556,
  9.789884226924931,
  9.704796557774676,
  10.069546045512471,
  10.38661542009992,
  9.852883235174211,
  9.958574367609767,
  11.295820709633261,
  9.675218845993529,
  9.538429897997771,
  9.701800110899498,
  10.31060650138159,
  10.738421742283709,
  8.803334654088214,
  10.01322424447365,
  8.243716094993745,
  9.621710842684365,
  9.003675309006342,
  8.559929356928787,
  10.735059757343246,
  9.732511545445819,
  9.279948811698985,
  9.618888923616353,
  9.86895993009805,
  8.971342846164523,
  9.453544908525746,
  10.108983165870734,
  9.835970855079053,
  8.17195321716235,
  9.95491945042087,
  9.995968662337463,
  9.970379066273399,
  8.630012446397393,
  9.909875938581541,
  10.347695332480313,
  9.488985898554578,
  8.62310464386578,
  8.82079064168341,
  8.66933457147812,
  9.88355701498947,
  10.114335222763412,
  9.356985957395498,
  9.064427422680648,
  8.294456495478254,
  8.267235272393776,
  8.159424921342309,
  9.954038146954955,
  8.94445690284401,
  8.721075395879,
  8.854840855148694,
  10.39298425044963,
  9.87774515829527,
  9.293684139795268,
  9.823669201497971,
  9.524839327310264,
  8.911355727748644,
  9.660835422093113,
  8.258047655718451,
  11.794695701687363,
  10.581820054268528,
  8.534544262467978,
  8.817185437465994,
  9.03486450838932,
  9.729928564722771,
  8.978446302931763,
  9.132357281486469,
  9.432637668381396,
  9.110936885843657,
  10.643156438942516,
  10.044037808908929,
  8.699320908770536,
  10.006904805315884,
  10.302027008725311,
  9.386112821482419,
  8.930450330383586,
  10.011103021099101,
  8.717398173591011,
  10.573115934494586,
  7.919964006988657,
  10.196119600670675,
  8.787435313189512,
  9.34597517852565,
  9.014339214894857,
  9.446369465646825,
  9.270856776531007,
  8.3626226150081,
  9.062190816979292,
  8.853072327848157,
  9.325019899211457,
  9.457088176133277,
  10.510285432967324,
  9.117252786906553,
  10.157192568189974,
  8.790772555276344,
  9.345819887684586,
  10.46890862720788,
  9.133406265916694,
  10.441072621726324,
  9.905105482325137,
  9.789024684367687,
  10.542761202836845,
  9.500764941292726,
  9.668115915756369,
  9.422756325436179,
  9.530933347687224,
  8.867668932636729,
  10.110624872165053,
  8.590184496499948,
  9.007246017817897,
  8.924542189464738,
  9.09985494849201,
  8.92044642127032,
  8.869458636212109,
  8.943595087568905,
  8.623400461223463,
  9.716597236686264,
  9.82639426455219,
  10.092948596752981,
  10.290174447723267,
  8.615370459270466,
  8.586017855346574,
  8.948658408056218,
  10.294725993492333,
  9.442403488879988,
  10.230647421166331,
  8.884589712823198,
  9.766477093462967,
  11.14650061469969,
  10.24287012007673,
  9.354192302725215,
  9.779973278336392,
  8.704712927786442,
  9.51758202249179,
  9.510023164830423,
  9.282603700064735,
  10.100367012145737,
  10.170009681285972,
  9.165446218745425,
  9.801040899660778,
  10.935792326759051,
  10.168120396648115,
  9.127085138440798,
  9.764944712877748,
  10.187183036077926,
  10.8011398101802,
  10.104453387113578,
  9.425222702329409,
  9.909100648044834,
  8.363073834283675,
  8.280871598479957,
  8.852560633370585,
  9.804305240090027,
  9.097599134842461,
  9.349074149926027,
  9.9398984963932,
  7.289166772241003,
  8.953439645836706,
  11.031929443274157,
  9.56940863151683,
  9.894970677573097,
  9.345070177632127,
  10.808687718614925,
  8.47354950244134,
  9.936417739415095,
  9.890950799566022,
  11.045738496077115,
  9.840157953782116,
  7.534565694088619,
  9.363199662958289,
  8.671125386303371,
  9.634834667361869,
  8.96707685042229,
  10.281122691150568,
  9.004113282011607,
  10.383204441293493,
  10.60501195562232,
  8.364567485778206,
  9.873543517843332,
  10.68270804075994,
  9.76724078045726,
  8.790856686652699,
  9.34363412111913,
  9.554719481377571,
  9.424796946999072,
  10.216056501866108,
  8.333457467466246,
  8.68040321568868,
  8.810279651291454,
  9.178670776911545,
  9.128124010404376,
  10.384552839183854,
  10.113941989030353,
  9.148894023868628,
  9.453507815529974,
  10.678859622741339,
  9.351852603973013,
  9.737817407701083,
  10.45984714447534,
  10.983608874026634,
  10.04223601428819,
  10.128495541318662,
  9.228765255298706,
  10.160753207024802,
  9.620629629723268,
  10.32164331849093,
  9.473770177118562,
  9.88842743973631,
  9.803751355876887,
  11.324243537331315,
  10.79589496610273,
  8.442743527624758,
  9.648227451024798,
  9.258877191339408,
  8.954505517165577,
  11.065606500227107,
  8.931507441065111,
  11.976683554100775,
  10.095947374864295,
  9.468358150207779,
  8.73148560946394,
  8.924025009016196,
  9.749035640087858,
  8.74317950551893,
  8.523062498736401,
  9.1363138582761,
  8.659328640560114,
  8.842622673421847,
  8.984591823220745,
  10.190497996281914,
  8.304470965839188,
  10.288304028896773,
  10.061641944048713,
  9.09985761181907,
  8.316572543981708,
  9.081715660550072,
  10.04929297980407,
  8.278804977771797,
  9.991415270188623,
  10.206615542033706,
  8.662646456246168,
  9.965232001843948,
  8.73637269857589,
  9.3226386405658,
  8.903197493082804,
  8.69966002710749,
  11.227337587331002,
  10.374655129542804,
  8.316101675315796,
  10.180371179564597,
  10.054625311993322,
  10.49883203684729,
  9.971042157853342,
  8.783523825409484,
  9.991173918493883,
  10.07450708401624,
  9.696211962602714,
  9.237966193025935,
  10.699962821837968,
  10.060530750601755,
  10.000823821865248,
  9.394047698987185,
  8.675232276709307,
  10.477397676377732,
  9.846989873109877,
  7.857979681244175,
  9.222665480675477,
  9.673083634957464,
  10.597702417914105,
  9.070348881220815,
  10.206479008005497,
  8.407543125087672,
  9.507354118133298,
  8.986200683093129,
  10.541681847082053,
  8.878162411390683,
  9.647052846236374,
  10.280586049918584,
  9.232099319060136,
  9.209649480876353,
  10.792750750227249,
  9.136700053395986,
  9.042217462722055,
  10.756041443484696,
  9.220550873548893,
  10.73200187098519,
  10.65012690146185,
  8.364333400616996,
  8.31358325960714,
  8.391920032151093,
  9.491381648676656,
  9.137527486603972,
  9.7662225134028,
  9.703505401896756,
  9.788195660161744,
  9.750300318901846,
  9.385543107496497,
  10.084155427552815,
  9.96592403914574,
  9.410532883615309,
  9.558174112873013,
  10.032107592403456,
  9.013380822743448,
  10.369008864283328,
  9.81637248726725,
  9.48964422644019,
  9.167217892849733,
  10.596093883615161,
  9.316932642012572,
  10.098351220600724,
  9.501409143139197,
  9.650522013374015,
  8.660481874035133,
  7.886131720366569,
  8.587730402531403,
  9.106814126349041,
  9.875237430184038,
  8.866639859060596,
  9.583153397974582,
  9.32632809954012,
  10.540153188879021,
  10.116849363945725,
  8.218031220878599,
  9.879046112346279,
  9.675118447861314,
  8.041424931532166,
  9.142315680280905,
  10.813068701408463,
  8.471481434087417,
  8.040684868410311,
  9.340838200833392,
  10.927037041474104,
  10.219730516822256,
  10.154163735646769,
  9.523773322278748,
  10.498090301904357,
  10.314700929442662,
  9.262342060554039,
  9.512215212268595,
  9.247855635540565,
  8.944648913599982,
  9.822915560152232,
  9.833067616798473,
  9.587891255389941,
  9.24379369231155,
  9.894854810664881,
  10.519834843314626,
  9.287317739484763,
  10.08148718148722,
  10.07288062176735,
  8.480103506791258,
  9.242631607297414,
  9.102276397644836,
  9.73138467207217,
  9.842956118407864,
  9.074553303571047,
  10.323391395941215,
  8.85028461248835,
  10.361213229630213,
  9.091367691933202,
  9.606599120199474,
  9.765982123898505,
  9.952290620614868,
  9.938220594195542,
  10.856421474812363,
  9.858354406622999,
  9.849303599758157,
  9.319305121591459,
  10.219309344423012,
  10.009825282256214,
  10.046913111082977,
  9.952413817993989,
  8.634729321591834,
  8.63869994061921,
  9.961900471846313,
  7.7478805736128615,
  10.16469351944785,
  11.277693845569633,
  9.45340842371133,
  9.62854974100163,
  10.068151602203502,
  8.981711366293071,
  9.409395957679816,
  9.962663221445855,
  9.035577338332653,
  9.189667585629977,
  9.36356829874522,
  9.635124559355454,
  9.54600235210942,
  9.159514269808726,
  10.185899297609657,
  8.588409822609,
  8.580800760581146,
  8.913129994470408,
  8.58400049273343,
  8.961176829221529,
  10.36933968103009,
  9.273014048173202,
  9.514371881329753,
  10.058090469616204,
  9.811505348292995,
  9.919342331971942,
  8.72689450618306,
  10.161755153664663,
  10.04983238252897,
  9.204060448282169,
  9.17027721902518,
  9.175113812185776,
  9.630748317398941,
  9.486994848280787,
  10.099619428049332,
  8.858577607659706,
  9.509440911940105,
  8.350567653353204,
  9.95169831536201,
  8.921658605186737,
  8.874042344611635,
  9.080997319520408,
  8.7046404400584,
  9.375270821584644,
  9.262161828916431,
  9.945581692053635,
  10.647794208780486,
  10.097097972230191,
  8.509637894475233,
  9.272194948557454,
  8.537961410337342,
  10.600972402707574,
  8.449352271860967,
  8.649682877686036,
  9.89378556946035,
  8.775321134350111,
  8.939540281620102,
  9.77140035395237,
  8.209263935811546,
  9.560302468075301,
  11.085050197395946,
  8.611013381879333,
  10.139658389563888,
  9.799917140134426,
  9.568833213616509,
  8.460078008266597,
  10.123903390180564,
  8.895229116322435,
  9.931350916235973,
  9.277662413221853,
  9.085017164876596,
  8.112981984754619,
  11.161578133208579,
  11.105713289084685,
  9.76691046179149,
  10.292812117329944,
  10.559332498233733,
  8.734782216123875,
  10.385682325904646,
  11.075551137834726,
  8.456197549633794,
  10.36485373242005,
  9.54532424980735,
  10.118712549781188,
  9.739699625672658,
  9.521171566237554,
  9.453468474398546,
  8.242187433955092,
  7.8639168911855455,
  9.244150238738204,
  8.263010012682845,
  9.195157575146059,
  9.572469350952325,
  9.971220739615585,
  9.001479258439993,
  8.46149041538394,
  9.554810522845637,
  9.093361208280648,
  10.357268282206098,
  9.945777456998417,
  8.008090054553527,
  8.855488327075573,
  8.694305150989136,
  9.182623206494732,
  7.93513705561735,
  8.965273814791727,
  9.323754282816141,
  8.455902129607246,
  10.695235220100146,
  9.347718240907229,
  9.108196917289233,
  10.334464339628001,
  8.70244430525714,
  9.682692786767834,
  9.430317820764419,
  9.740056628261183,
  8.971963767355378,
  8.530198234664596,
  10.13665268089744,
  9.008647162970506,
  9.925932892310634,
  10.9487460311751,
  10.135658598337262,
  9.502072313571976,
  9.13972352253847,
  9.808674257362348,
  11.05201690600861,
  9.529178601250191,
  10.286706202845362,
  8.866899384914342,
  9.467638352121515,
  8.188297329303726,
  9.07005687704733,
  9.841413275338475,
  10.342705464327944,
  9.113362667059748,
  9.184349437771237,
  9.15395555977208,
  10.586804032929932,
  10.798036112876467,
  9.784681942628021,
  8.732002200795174,
  10.699616424315485,
  9.04619654787351,
  9.840253970836008,
  10.181839231871528,
  8.609595240110714,
  9.021285325479953,
  9.27430481105283,
  9.735047897298498,
  9.825654693941612,
  10.039833714308806,
  7.899356613087642,
  8.71262525414853,
  10.21738061415058,
  9.269361931888673,
  10.620378183408569,
  8.26382281724741,
  9.401601949332282,
  10.102403527885327,
  10.247077295033284,
  9.406579929174569,
  10.528533241275523,
  9.925770820673575,
  9.16384686300634,
  9.34307370832676,
  9.819039626407106,
  9.70833948407965,
  9.279971602125686,
  8.747955390316745,
  9.903662210000975,
  9.665476398633396,
  10.546855298503212,
  9.302218452045276,
  9.243469088014884,
  10.034812609440353,
  9.987789514899648,
  10.606861631771606,
  9.2198343393772,
  9.101469216658176,
  9.142936070516443,
  8.643923083276041,
  8.997325365954975,
  9.505932273078496,
  9.165516463650835,
  9.094061727969589,
  9.923711152494313,
  9.589221665628557,
  9.019025802364686,
  9.759234383245769,
  10.14087134471659,
  8.55410374668737,
  10.443218625309362,
  10.09269577694567,
  10.637111762890214,
  7.821713346413225,
  10.87551953382534,
  8.757751251775954,
  9.853341045934757,
  11.300468900652225,
  8.330891392738032,
  9.92321495664372,
  8.55114639619347,
  9.125202357441907,
  8.936198841720506,
  8.17399889776532,
  9.290125137928438,
  9.480569596941164,
  10.823882707838292,
  9.220321134647037,
  9.330193946001895,
  9.352350025137289,
  9.195027195751871,
  9.942081356568503,
  10.85120106067746,
  8.074354968074552,
  9.250753409826965,
  8.724551923714618,
  9.427576537638968,
  8.816898861739316,
  9.578570097206864,
  10.121545983217514,
  9.503248082885628,
  10.186428879655113,
  9.2630593937016,
  8.132282604725065,
  9.24915158073579,
  9.481959034210007,
  9.082821251610907,
  8.997912375433952,
  9.75038243228221,
  9.717589729129244,
  8.33571197530953,
  9.236785152191935,
  8.49436921799984,
  9.383649255712406,
  7.741270135437877,
  9.1201654231638,
  9.860221552122892,
  8.17835304982782,
  9.167864647898897,
  10.268745297089078,
  9.569406979259046,
  9.129993161586512,
  9.587575679281816,
  8.771522477313185,
  9.922016040041994,
  9.380461902496045,
  9.270071468231693,
  9.479269412214302,
  8.08039758735927,
  9.81549313180877,
  9.041271491202906,
  9.075629313712435,
  9.8920886761969,
  10.53574707081208,
  9.91927153801264,
  9.829027681412057,
  9.178109576009497,
  11.02853562658595,
  9.45110731917251,
  11.242657456998426,
  9.644537101992153,
  9.27441202962742,
  9.811424417420033,
  8.843809020650005,
  9.439323401602564,
  10.652364602758114,
  8.512633613311618,
  9.552905459430832,
  8.776211124433317,
  10.307917262674762,
  8.3249431631888,
  8.843924077601903,
  10.213485603808614,
  9.07893017553191,
  10.081447095309667,
  9.774151770983263,
  9.18008708864289,
  9.570990791633973,
  10.57265966998785,
  8.84710200486775,
  10.071250732357033,
  9.169813294831522,
  8.900806603317205,
  8.38312594291131,
  10.66699908479051,
  9.391761610829457,
  9.78451069444868,
  10.205163328846972,
  10.142579241768267,
  9.5342798861114,
  10.296256763053309,
  8.924401964163916,
  8.992664314939773,
  9.192815938395619,
  9.40460094386097,
  10.205495967826392,
  9.360264653775273,
  10.051722222169762,
  10.57272601665235,
  11.188282028147992,
  9.346176654882107,
  9.311382355281555,
  9.316513439155473,
  9.529173179442354,
  9.230190371953757,
  9.55588140001975,
  9.418688995305141,
  10.674084300448566,
  9.989091578399458,
  10.604328190483043,
  8.554079821706937,
  9.205249657905417,
  9.804454759156517,
  9.938453006293647,
  9.466608367371665,
  9.135905246952582,
  8.774921312689198,
  9.845479589058014,
  8.365316160929561,
  10.562456550830984,
  10.182702020015224,
  9.188656265784562,
  11.215734168867789,
  8.280212113447227,
  9.311043318427771,
  9.400767581741095,
  8.5876719371373,
  8.571552515508689,
  9.74635464299672,
  9.121364828946254,
  9.73495034346119,
  9.18691886041549,
  8.739729099551216,
  9.779327683163693,
  9.433455227057513,
  9.877649156580805,
  10.568315641280327,
  8.881727485368312,
  9.646142243824096,
  9.774433447330898,
  9.940580527442576,
  10.503466860611026,
  9.503316802610744,
  8.444610499390476,
  9.167562309242022,
  11.57123321152623,
  9.910729927635861,
  10.171277164329219,
  10.361594815151532,
  8.328112541454685,
  9.407791307794493,
  8.928739758675965,
  10.036063757495475,
  9.393198922513575,
  8.278630854619852,
  10.90681806260578,
  9.248729167976027,
  8.38799826479966,
  9.831507859931534,
  9.594608464428571,
  9.161617624633765,
  10.067657549134545,
  9.089012295131136,
  8.721210107956718,
  9.344061606393401,
  9.868395380061568,
  8.741951028502962,
  10.002666768241808,
  8.594388748466647,
  9.583585943697166,
  9.695624493864168,
  9.118491953541005,
  8.265382682501292,
  9.843949777293075,
  9.881173320706145,
  8.81248575074624,
  10.426562402810784,
  8.922778833894728,
  9.87899057101455,
  9.881142547467105,
  9.260033203475414,
  8.37807463485805,
  8.449861869206675,
  8.95962218377935,
  9.05283618824519,
  9.08112147127606,
  9.165333165093797,
  8.841641440039968,
  8.348778678380759,
  9.993449986527619,
  9.32596786853531,
  9.283993615940023,
  9.216414873568498,
  8.295597210092854,
  9.02241128637933,
  8.731708892172165,
  8.761242765959363,
  9.150488278593505,
  7.4823888800048115,
  11.42213972745477,
  9.790453178768772,
  10.15790723598311,
  9.939040728533529,
  9.261013641481782,
  8.719377269544657,
  9.35945569219877,
  9.10981872871875,
  9.572029196921019,
  10.339049419287141,
  9.178668727728176,
  10.11755790713252,
  9.312645192881867,
  9.00803223295917,
  8.691214476576183,
  9.007932228771487,
  9.71925301417784,
  9.302353034730439,
  9.386005138685327,
  9.090371529561075,
  8.945452572202571,
  8.90470867128039,
  10.00026832189651,
  10.674109370539163,
  8.56541129335579,
  8.576640268435442,
  9.534629963164946,
  10.432470144710296,
  9.412329379987018,
  8.53761265647463,
  8.702294968687747,
  10.298246758469526,
  9.03519429773982,
  8.798615598778477,
  9.229181715681287,
  8.382594434075049,

In [199]:
confidence_intervals = {}

for i in time_series_stats.columns[1:]:
    values = bootstrap_std[f'{i}_bootstrap_std']
    confidence_intervals[f'{i} Bootstrap 90% CI for STD'] = np.percentile(values, [5, 95])

confidence_intervals

{'min_1 Bootstrap 90% CI for STD': array([ 8.29554017, 10.70696541]),
 'max_1 Bootstrap 90% CI for STD': array([3.37557978, 5.25635483]),
 'mean_1 Bootstrap 90% CI for STD': array([4.70029928, 5.84702326]),
 'median_1 Bootstrap 90% CI for STD': array([4.75907312, 5.94485829]),
 'std_1 Bootstrap 90% CI for STD': array([1.56497475, 1.94771034]),
 '1st_quart_1 Bootstrap 90% CI for STD': array([5.57257146, 6.60260065]),
 '3rd_quart_1 Bootstrap 90% CI for STD': array([4.35224046, 5.82294189]),
 'min_2 Bootstrap 90% CI for STD': array([0., 0.]),
 'max_2 Bootstrap 90% CI for STD': array([4.63550416, 5.41190332]),
 'mean_2 Bootstrap 90% CI for STD': array([1.40183004, 1.7082013 ]),
 'median_2 Bootstrap 90% CI for STD': array([1.23638606, 1.54659236]),
 'std_2 Bootstrap 90% CI for STD': array([0.80585319, 0.93796487]),
 '1st_quart_2 Bootstrap 90% CI for STD': array([0.83805542, 1.03825866]),
 '3rd_quart_2 Bootstrap 90% CI for STD': array([1.9058205 , 2.29155555]),
 'min_3 Bootstrap 90% CI for STD': array([2.75242437, 3.10728183]),
 'max_3 Bootstrap 90% CI for STD': array([4.2095115 , 5.50340149]),
 'mean_3 Bootstrap 90% CI for STD': array([3.40194732, 4.53916098]),
 'median_3 Bootstrap 90% CI for STD': array([3.41312019, 4.53087198]),
 'std_3 Bootstrap 90% CI for STD': array([0.75488567, 1.11700852]),
 '1st_quart_3 Bootstrap 90% CI for STD': array([3.60064225, 4.69800057]),
 '3rd_quart_3 Bootstrap 90% CI for STD': array([3.54902532, 4.67948273]),
 'min_4 Bootstrap 90% CI for STD': array([0., 0.]),
 'max_4 Bootstrap 90% CI for STD': array([1.96955987, 2.36560824]),
 'mean_4 Bootstrap 90% CI for STD': array([1.08173401, 1.22293898]),
 'median_4 Bootstrap 90% CI for STD': array([1.05566708, 1.20156237]),
 'std_4 Bootstrap 90% CI for STD': array([0.42169974, 0.48624374]),
 '1st_quart_4 Bootstrap 90% CI for STD': array([0.77378697, 0.89132106]),
 '3rd_quart_4 Bootstrap 90% CI for STD': array([1.42459544, 1.63281134]),
 'min_5 Bootstrap 90% CI for STD': array([4.37515002, 7.5069241 ]),
 'max_5 Bootstrap 90% CI for STD': array([4.73197538, 6.65507539]),
 'mean_5 Bootstrap 90% CI for STD': array([4.39178138, 6.71239373]),
 'median_5 Bootstrap 90% CI for STD': array([4.46348286, 6.89823821]),
 'std_5 Bootstrap 90% CI for STD': array([0.82137871, 1.22136115]),
 '1st_quart_5 Bootstrap 90% CI for STD': array([4.81286783, 7.20872865]),
 '3rd_quart_5 Bootstrap 90% CI for STD': array([4.37247878, 6.45667014]),
 'min_6 Bootstrap 90% CI for STD': array([0.        , 0.07847613]),
 'max_6 Bootstrap 90% CI for STD': array([2.25375367, 2.77041181]),
 'mean_6 Bootstrap 90% CI for STD': array([1.06440329, 1.21668131]),
 'median_6 Bootstrap 90% CI for STD': array([0.99113827, 1.15009477]),
 'std_6 Bootstrap 90% CI for STD': array([0.47537519, 0.54372458]),
 '1st_quart_6 Bootstrap 90% CI for STD': array([0.68926038, 0.80588243]),
 '3rd_quart_6 Bootstrap 90% CI for STD': array([1.40186207, 1.60205346])}

#### iv. Select Features

I would select median, max, and STD as my time domain features. Min has 0 variability for some of the features. I thought first quartile and third quaritle looked very similiar with very little variability. Although the median and mean are very similiar, I chose median because it is affected less by outliers.

## 2. ISLR 3.7.4

### (a) Linear Train

We would expect the training RSS for the cubic regression to be lower than the training RSS for the linear regression. Since the cubic model includes the linear model, the cubic model can become the linear model by setting the other variables to 0. Therefore, it will have the same or lower RSS. The cubic model may also try to account for the noise with its other variables, which would result in a lower training RSS.

### (b) Linear Test

We would expect the testing RSS for the linear regression to be smaller because the true relationship is linear.

### (c) Not Linear Train

The result is still the same. Although we may not know the true relationship anymore, the cubic model still contains the linear model. Therefore, we know it will perform as well as the linear model, but it may perform even better depending on the noise. The cubic model will be more flexible, so it will have a lower RSS.

### (d) Not Linear Testing

Without knowing the true relationship, we do not have enough information to tell which testing RSS would be smaller. If the true relationship was linear, the cubic model could overfit on the training and perform poorly. Or if the true relationship was non-linear, the cubic model could capture the more complex relationship and perform better on the test data. Without the true relationship, we cannot tell.

## 3. ISLR 3.7.3 - Extra Practice

## 3. ISLR 3.7.5 - Extra Practice